name: GitHub Classroom Workflow

on:
  - push
  - workflow_dispatch

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - run: |
          python -m pip install --upgrade pip
          pip install numpy==1.21.0
          pip install -r requirements.txt
      - name: Run scraping script to generate lego2019.csv
        run: python si-exercise.py

      - uses: education/autograding@v1